config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/JanPremus/fd3d_TSN:
      branch: master
      repo: https://github.com/JanPremus/fd3d_TSN.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/JanPremus/fd3d_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-vermilion-millipede.sh
        container: qc.acc_fuzzy-lilac-earwig
  QC.Doc:
    repos:
      github.com/JanPremus/fd3d_TSN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-cornflower-ladybird.sh
        container: qc.doc_flimsy-ochre-heron
      github.com/JanPremus/fd3d_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-eggplant-wasp.sh
        container: qc.doc_trippy-dandelion-wrasse
  QC.Lic:
    repos:
      github.com/JanPremus/fd3d_TSN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-smalt-corgi.sh
        container: qc.lic_grumpy-tangerine-lemming
  QC.Ver:
    repos:
      github.com/JanPremus/fd3d_TSN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-persimmon-squirrel.sh
        container: qc.ver_scaly-maroon-olm
timeout: 5400
