config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/JanPremus/fd3d_TSN:
      branch: master
      repo: https://github.com/JanPremus/fd3d_TSN.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/JanPremus/fd3d_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-chocolate-sheepdog.sh
        container: qc.acc_chewy-taupe-mastiff
  QC.Doc:
    repos:
      github.com/JanPremus/fd3d_TSN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-corn-capybara.sh
        container: qc.doc_shabby-burgundy-fossa
      github.com/JanPremus/fd3d_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lemon-coral.sh
        container: qc.doc_sunny-cerise-eel
  QC.Lic:
    repos:
      github.com/JanPremus/fd3d_TSN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-bistre-hound.sh
        container: qc.lic_greasy-cinnabar-corgi
  QC.Ver:
    repos:
      github.com/JanPremus/fd3d_TSN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-goldenrod-chinook.sh
        container: qc.ver_snazzy-olivine-kiwi
timeout: 5400
